---
title: "About"
---
Gilbert Akuja 

Welcome to my profile page. Here i talk about myself and my accomplishments. 

I was a student at Charles H. Dyson school of Applied Economic and Management at Cornell University. My academic concentrations were finance and business analytics. I enjoyed corporate finance, financial markets and institutions and financial services analytics. I am keen on using my business aptitude in the field of financial services. My end goal is to start an enterprise of my own. Through my time in and outside class I have developed a number of skills that include:

Analytical skills: I am skilled in analyzing data sets and formulating data sets in Microsoft Excel. These skills result directly from various high school computer courses and my current spreadsheet modeling course. This course has required me to think critically when creating formulas and evaluating data sets.

Team work: Through academics and extracurricular activities, I have learnt how to work in teams to accomplish projects. I bring a sense of responsibility in every team I work in. I believe team work is key to success in any business. 

Communication skills: My experience in customer service has strengthened my ability to interact and converse with various types of people. I have the confidence to approach customers, discover their specific requests, then provide proper recommendations based on their descriptions. 

I am eager to expand my knowledge and network in future internships and opportunities. Please feel free to connect with me at gilbertakuja12@gmail.com with any inquiries and potential opportunities.
